stages:
  - test
  - release


linters:
  image: python:3.8-slim-buster
  stage: test
  script:
    - apt install make
    - pip install -r requirements_dev.txt
    - make lint


pytest:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements_dev.txt
    - pytest --cov=truechecker/ tests/
    - coverage xml
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    reports:
      cobertura: coverage.xml
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'


pypi:
  image: python:3.8
  stage: release
  script:
    - pip install -U twine poetry
    - poetry build
    - poetry publish --username $TWINE_USERNAME --password $TWINE_PASSWORD
  only:
    - tags
