stages:
  - test
  - release


linters:
  image: python:3.9-slim
  stage: test
  script:
    - pip install -U poetry
    - poetry install
    - poetry run isort . --profile black
    - poetry run black .
    - poetry run mypy -p truechecker
    - poetry run flake8 .
    - poetry run pylint truechecker --ignored-modules=pydantic
    - poetry run pydocstyle truechecker


pytest:
  stage: test
  image: python:3.9-slim
  script:
    - pip install -U poetry
    - poetry install
    - poetry run pytest --cov=truechecker/ tests/
    - poetry run coverage xml
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    reports:
      cobertura: coverage.xml
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'


pypi:
  image: python:3.9
  stage: release
  script:
    - pip install -U twine poetry
    - poetry build
    - poetry publish --username $TWINE_USERNAME --password $TWINE_PASSWORD
  only:
    - tags
